Fix a null error
This was the cause of the following error in the console:
```
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "ca.uwindsor.css.ctf.TeamManager.getPlayerTeam(org.bukkit.entity.Player)" is null
```

This should not normally be a problem if everyone on a server is participating in CTF